OTIS_POC/Controllers/ContractsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OTIS_POC.Controllers
{
    public class ContractsController : Controller
    {
        // GET: Contracts
        public ActionResult New()
        {
            return View();
        }
    }
}

OTIS_POC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - OTIS</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/fontawesome")
    @Styles.Render("~/Content/3rdpartycss")
    @Styles.Render("~/Content/fonts")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    
    <div class="body-home">

        <div class="body-wrapper">

            <div>

                <div class="sidebar-wrapper">

                    <section class="sidebar-vertical" style="width:200px">
                        <ul class="sidebar-menu">
                            <li class="sidebar-header">OTIS CHINA</li>
                            <li>
                                <a href="@Url.Action("Index", "Home")">
                                    <i class="fa fa-home"></i> <span>Home</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="fa fa-pencil-square-o"></i> <span>Contracts</span> <i class="fa fa-angle-right pull-right"></i>
                                </a>
                                <ul class="sidebar-submenu">
                                    <li><a href="@Url.Action("New", "Contracts")"><i class="fa fa-file-o"></i> New</a></li>
                                    @*<li><i class="fa fa-file-o"></i>@Html.ActionLink("New", "New", "Contracts", new { @class = "fa fa-file-o" })</li>*@
                                    <li><a href="#"><i class="fa fa-search"></i> Search</a></li>
                                    <li><a href="#"><i class="fa fa-check-square-o"></i> My Contracts</a></li>
                                    <li><a href="#"><i class="fa fa-pencil"></i> Amend</a></li>
                                    <li><a href="#"><i class="fa fa-wrench"></i> Change Status</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="fa fa-gavel"></i> <span>Approvals</span></i>
                                    <span class="label label-primary pull-right">5</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="fa fa-pie-chart"></i> <span>Evaluation</span></i>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="fa fa-money"></i> <span>Payments</span> <i class="fa fa-angle-right pull-right"></i>
                                </a>
                                <ul class="sidebar-submenu">
                                    <li><a href="#"><i class="fa fa-file-o"></i> New</a></li>
                                    <li><a href="#"><i class="fa fa-search"></i> Search</a></li>
                                    <li><a href="#"><i class="fa fa-check-square-o"></i> Approve</a></li>
                                    <li><a href="#"><i class="fa fa-balance-scale"></i> Balance</a></li>
                                    <li><a href="#"><i class="fa fa-credit-card"></i> My Payments</a></li>
                                    <li><a href="#"><i class="fa fa-shopping-bag"></i> Orders</a></li>
                                    <li><a href="#"><i class="fa fa-shopping-basket"></i> My Orders</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="fa fa-database"></i>
                                    <span>Master Data</span><i class="fa fa-angle-right pull-right"></i>
                                </a>
                                <ul class="sidebar-submenu" style="display: none;">
                                    <li><a href="#"><i class="fa fa-users"></i> Users</a></li>
                                    <li><a href="#"><i class="fa fa-map-marker"></i> Venues</a></li>
                                    <li><a href="#"><i class="fa fa-archive"></i> Wholesalers</a></li>
                                    <li><a href="#"><i class="fa fa-beer"></i> Brands</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="fa fa-keyboard-o"></i>
                                    <span>Monthly Input</span><i class="fa fa-angle-right pull-right"></i>
                                </a>
                                <ul class="sidebar-submenu" style="display: none;">
                                    <li><a href="#"><i class="fa fa-square"></i> SAP</a></li>
                                    <li><a href="#"><i class="fa fa-stack-overflow"></i> Stock Movement</a></li>
                                </ul>
                            </li>


                        </ul>
                    </section>

                </div>                         

            </div>

            <div>

                <div class="content-wrapper">

                    <div class="navbar navbar-default navbar-fixed-top">
                        <div class="container-fluid">
                            <div class="navbar-header">
                                <a class="navbar-brand" href="#">
                                    <img id="logo" src="~/Content/Images/diageo-logo.png" alt="Diageo" />
                                </a>
                            </div>
                           @*@Html.Partial("~/Views/_UserDetails.cshtml")*@
                            @{
                                Html.RenderAction("LayoutData", "Home");
                            }
                        </div>
                    </div>

                    <div class="body-content-wrapper">

                        <div class="container body-content">

                            @RenderBody()
                            <hr />
                        </div>

                    </div>

                </div>
            
            </div>

        </div>

    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/3rdpartyjs")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script>
        
    </script>
</body>
</html>